# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-18 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20160718_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereplay',
            name='build',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hearthstone Build'),
        ),
        migrations.AlterField(
            model_name='gamereplay',
            name='hsreplay_version',
            field=models.CharField(help_text='The HSReplay spec version of the HSReplay XML file', max_length=8, verbose_name='HSReplay version'),
        ),
    ]
