# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-07-28 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import hearthstone.enums
import hsreplaynet.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20160718_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalgame',
            name='format',
            field=hsreplaynet.utils.fields.IntEnumField(choices=[(0, 'FT_UNKNOWN'), (1, 'FT_WILD'), (2, 'FT_STANDARD')], default=0, validators=[hsreplaynet.utils.fields.IntEnumValidator(hearthstone.enums.FormatType)], verbose_name='Format type'),
        ),
        migrations.AlterField(
            model_name='globalgame',
            name='brawl_season',
            field=models.IntegerField(default=0, help_text='The brawl season which increments every time the brawl changes.', verbose_name='Tavern Brawl season'),
        ),
        migrations.AlterField(
            model_name='globalgame',
            name='game_handle',
            field=models.IntegerField(blank=True, help_text='Game ID on the Battle.net server', null=True, verbose_name='Game handle'),
        ),
        migrations.AlterField(
            model_name='globalgame',
            name='game_type',
            field=hsreplaynet.utils.fields.IntEnumField(blank=True, choices=[(0, 'BGT_UNKNOWN'), (1, 'BGT_FRIENDS'), (2, 'BGT_RANKED_STANDARD'), (3, 'BGT_ARENA'), (4, 'BGT_VS_AI'), (5, 'BGT_TUTORIAL'), (6, 'BGT_ASYNC'), (9, 'BGT_NEWBIE'), (7, 'BGT_CASUAL_STANDARD'), (8, 'BGT_TEST1'), (10, 'BGT_TEST3'), (16, 'BGT_TAVERNBRAWL_PVP'), (17, 'BGT_TAVERNBRAWL_1P_VERSUS_AI'), (18, 'BGT_TAVERNBRAWL_2P_COOP'), (30, 'BGT_RANKED_WILD'), (31, 'BGT_CASUAL_WILD'), (32, 'BGT_LAST')], null=True, validators=[hsreplaynet.utils.fields.IntEnumValidator(hearthstone.enums.BnetGameType)], verbose_name='Game type'),
        ),
        migrations.AlterField(
            model_name='globalgame',
            name='match_end',
            field=models.DateTimeField(help_text='Must be a timezone aware datetime.', verbose_name='Match end'),
        ),
        migrations.AlterField(
            model_name='globalgame',
            name='match_start',
            field=models.DateTimeField(help_text='Must be a timezone aware datetime.', verbose_name='Match start'),
        ),
    ]
